/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patient.registry.management.system;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
/**
 *
 * @author jeany
 */
public class UserRegistry extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public UserRegistry() {
        initComponents();
        setLocationRelativeTo(this);
        setIconImage();
        clearAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        password_pf = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        fName_tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        uType_cbx = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        username_tf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lName_tf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        email_tf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        phone_tf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        confirmPass_pf = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Patient Registery");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Management System");

        jLabel3.setFont(jLabel3.getFont());
        jLabel3.setText("User type");

        jLabel4.setFont(jLabel4.getFont());
        jLabel4.setText("Password");

        password_pf.setText("defaultpassword");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patient/registry/management/system/resources/images/logo.png"))); // NOI18N

        fName_tf.setToolTipText("e.g: john-smith");

        jLabel6.setFont(jLabel6.getFont());
        jLabel6.setText("First Name");

        uType_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Admin", "Doctor", "Nurse", "Reception" }));
        uType_cbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uType_cbxActionPerformed(evt);
            }
        });

        jLabel8.setFont(jLabel8.getFont());
        jLabel8.setText("Username");

        username_tf.setToolTipText("e.g: john-smith");

        jLabel9.setFont(jLabel9.getFont());
        jLabel9.setText("Last Name");

        lName_tf.setToolTipText("e.g: john-smith");

        jLabel10.setFont(jLabel10.getFont());
        jLabel10.setText("Email");

        email_tf.setToolTipText("e.g: john-smith");

        jLabel11.setFont(jLabel11.getFont());
        jLabel11.setText("Phone");

        phone_tf.setToolTipText("e.g: john-smith");

        jLabel12.setFont(jLabel12.getFont());
        jLabel12.setText("Confirm Password");

        confirmPass_pf.setText("defaultpassword");

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(password_pf)
                    .addComponent(fName_tf)
                    .addComponent(uType_cbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(username_tf)
                    .addComponent(lName_tf)
                    .addComponent(email_tf)
                    .addComponent(phone_tf)
                    .addComponent(confirmPass_pf)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(uType_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fName_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lName_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(email_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(phone_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(username_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(password_pf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(confirmPass_pf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DBConnect dataLink = new DBConnect();
        String uType = uType_cbx.getSelectedItem().toString();
        String uFName = fName_tf.getText();
        String uLName = lName_tf.getText();
        String uEmail = email_tf.getText();
        String uPhone = phone_tf.getText();
        String uUsername = username_tf.getText();
        String uPassword = password_pf.getText();
        String uConfPass = confirmPass_pf.getText();
        
        if(uType_cbx.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Please choose a USER-TYPE", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }else if(uFName.isEmpty()){
            fName_tf.setBorder(BorderFactory.createLineBorder(Color.yellow));            
            JOptionPane.showMessageDialog(null, "First Name required", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }else if(uLName.isEmpty()){
            lName_tf.setBorder(BorderFactory.createLineBorder(Color.yellow));            
            JOptionPane.showMessageDialog(null, "Last Name required", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }else if(uEmail.isEmpty() || !uEmail.contains("@")){
            email_tf.setBorder(BorderFactory.createLineBorder(Color.yellow));            
            JOptionPane.showMessageDialog(null, "Email required", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }else if(uPhone.isEmpty()){
            phone_tf.setBorder(BorderFactory.createLineBorder(Color.yellow));            
            JOptionPane.showMessageDialog(null, "Phone Number required", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }else if(uUsername.isEmpty()){
            username_tf.setBorder(BorderFactory.createLineBorder(Color.yellow));            
            JOptionPane.showMessageDialog(null, "Username required", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }else if(uPassword.isEmpty()){
            password_pf.setBorder(BorderFactory.createLineBorder(Color.yellow));            
            JOptionPane.showMessageDialog(null, "Password required", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }else if(!uPassword.equals(uConfPass)){
            password_pf.setBorder(BorderFactory.createLineBorder(Color.yellow));
            confirmPass_pf.setBorder(BorderFactory.createLineBorder(Color.yellow));            
            JOptionPane.showMessageDialog(null, "Your Passwords DO NOT match", "Warning", JOptionPane.ERROR_MESSAGE);
        }else{
            String insert = "INSERT INTO user(userType,firstName,"
                + "lastName,email,phone,username,password) VALUES"
                + "('"+uType+"','"+uFName+"','"+uLName+"','"+uEmail+"','"+uPhone+"',"
                + "'"+uUsername+"','"+uPassword+"')";
            dataLink.updateTable(insert);
            clearAll();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       new Login().setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void uType_cbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uType_cbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uType_cbxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        clearAll();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegistry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegistry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegistry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegistry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRegistry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPass_pf;
    private javax.swing.JTextField email_tf;
    private javax.swing.JTextField fName_tf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lName_tf;
    private javax.swing.JPasswordField password_pf;
    private javax.swing.JTextField phone_tf;
    private javax.swing.JComboBox<String> uType_cbx;
    private javax.swing.JTextField username_tf;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("resources/images/logo.png")));
    }
    
    private void clearAll(){
        uType_cbx.setSelectedIndex(0);
        fName_tf.setText("");
        lName_tf.setText("");
        email_tf.setText("");
        phone_tf.setText("");
        username_tf.setText("");
        password_pf.setText("");
        confirmPass_pf.setText("");
       
    }
}
